name: Multi-Arch Kaniko Build

on:
  push:
    branches: ['pj/test']

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build ${{ matrix.arch }}
        run: |
          docker run --rm -v "$PWD:/busybox/workspace" -w /busybox/workspace kaniko-ci-toolkit:test \
            /kaniko/executor \
              --dockerfile=/busybox/workspace/Dockerfile \
              --destination=local \
              --no-push
