name: Test Docker Build

on:
  pull_request:
    branches: ['main']
    paths:
      - 'Dockerfile'
      - '.github/workflows/test-build.yaml'

jobs:
  test-build:
    name: Test Docker Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Test multi-platform build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          load: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and load image for testing
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: kaniko-ci-toolkit:test

      - name: Test image
        run: |
          echo "Running basic tests on the built image..."
          
          # Test that the image runs
          docker run --rm kaniko-ci-toolkit:test /busybox/sh -c "echo 'Container started successfully'"
          
          # Test that all tools are available
          echo "Testing tool availability..."
          
          # Test specific tools
          echo "Testing JQ..."
          docker run --rm kaniko-ci-toolkit:test /busybox/jq --version
          
          echo "Testing Make..."
          docker run --rm kaniko-ci-toolkit:test /busybox/make --version
          
          echo "Testing Bash..."
          docker run --rm kaniko-ci-toolkit:test /busybox/bash --version
          
          echo "Testing Crane..."
          docker run --rm kaniko-ci-toolkit:test /busybox/crane version
          
          echo "Testing Vault..."
          docker run --rm kaniko-ci-toolkit:test /busybox/vault version
          
          echo "Testing Manifest-Tool..."
          docker run --rm kaniko-ci-toolkit:test /busybox/manifest-tool --version
          
          echo "Testing Cosign..."
          docker run --rm kaniko-ci-toolkit:test /busybox/cosign version
          
          echo "Testing Oras..."
          docker run --rm kaniko-ci-toolkit:test /busybox/oras version
          
          echo "Testing Kaniko executor..."
          docker run --rm kaniko-ci-toolkit:test /kaniko/executor version
          
          echo "All tests passed!"
